# Hikes (D-31): a walk through the Hikes screens in the page's preview mode (sample data, no database, no network).
# Needs python3 with Playwright and Chromium. From the repository root:
#   python3 -m http.server 8765 &        then        python3 supabase/tests/hikes/preview_walk.py [folder for pictures]
# It opens index.html at phone size (390 x 844) and at desktop size (1280 x 800) as Eretz Israel Tours, then as a guide and
# as an organisation ("View as"), and checks what each sees and can do: the list by region, a hike's page, the route file,
# a report, adding a hike, the Review queue. Prints the failures, any page error, and the total. Pictures are saved too.
import asyncio, json, os, sys
from playwright.async_api import async_playwright
OUT=(sys.argv[1] if len(sys.argv)>1 else '/tmp/hikes_preview').rstrip('/')+'/'; os.makedirs(OUT, exist_ok=True)
res=[]; errs=[]
def check(n,c,d=''):
    res.append((n,bool(c))); print(('PASS ' if c else 'FAIL ')+n+((' :: '+str(d)[:300]) if not c else ''))
async def run(p, w, h, tag):
    b=await p.chromium.launch(); ctx=await b.new_context(viewport={'width':w,'height':h}, device_scale_factor=2, accept_downloads=True)
    await ctx.add_init_script("try{localStorage.setItem('eitv_tour_seen','1')}catch(e){}")
    pg=await ctx.new_page()
    pg.on('pageerror', lambda e: errs.append(tag+' pageerror: '+str(e)))
    pg.on('console', lambda m: errs.append(tag+' console: '+m.text) if m.type=='error' and 'Failed to load resource' not in m.text and 'net::' not in m.text else None)
    await pg.goto('http://localhost:8765/index.html'); await pg.wait_for_selector('.tabs')
    tabs=await pg.eval_on_selector_all('.tab', 'els=>els.map(e=>e.textContent.trim())')
    check(tag+': tabs are Suppliers, Quotes, Hikes, Jobs, Review, Team', [t.rstrip('0123456789') for t in tabs]==['Suppliers','Quotes','Hikes','Jobs','Review','Team'], tabs)
    over=await pg.evaluate("()=>document.documentElement.scrollWidth>innerWidth+1")
    check(tag+': no sideways scroll on the first screen', not over)
    await pg.click('.tab[data-tab="hikes"]'); await pg.wait_for_selector('#hkResults .row')
    rows=await pg.eval_on_selector_all('#hkResults .row .row-name','els=>els.map(e=>e.textContent)')
    check(tag+': Eretz Israel Tours sees all 8 sample hikes, the waiting one too', len(rows)==8 and 'Nahal Amud, upper part' in rows, rows)
    regs=await pg.eval_on_selector_all('.hk-reg','els=>els.map(e=>e.textContent)')
    check(tag+': grouped by region in the app\'s region order', [r.split(' · ')[0] for r in regs]==['Jerusalem','Binyamin & Shomron','Dead Sea & Judean Desert','Negev & Arava','Eilat','Galilee'], regs)
    check(tag+': the no-responsibility message is on the tab', 'take no responsibility' in await pg.inner_text('#view'))
    check(tag+': no sideways scroll on the Hikes tab', not await pg.evaluate("()=>document.documentElement.scrollWidth>innerWidth+1"))
    await pg.screenshot(path=OUT+tag+'_1_list.png')
    # filter by region
    await pg.click('[data-hreg="Jerusalem"]'); rows=await pg.eval_on_selector_all('#hkResults .row .row-name','els=>els.map(e=>e.textContent)')
    check(tag+': region filter', rows==['Nahal Katlav','Sataf springs loop'], rows)
    await pg.click('[data-hreg="All"]'); await pg.fill('#hq','og'); rows=await pg.eval_on_selector_all('#hkResults .row .row-name','els=>els.map(e=>e.textContent)')
    check(tag+': search', rows==['Nahal Og, lower canyon'], rows); await pg.fill('#hq','')
    # a hike's page
    await pg.click('#hkResults .row:has-text("Nahal Og")'); await pg.wait_for_selector('.sheet .hk-rep')
    t=await pg.inner_text('.sheet')
    check(tag+': hike page shows distance, time, start, end, markers, route file', all(x in t for x in ('5 km','3–4 hours','Og trailhead','Road 90','Blue, trail 9456','Black, trail 9452','On file')), t[:600])
    check(tag+': warnings for cliffs and firing zone', 'Not for a fear of heights' in t and 'Crosses a firing zone' in t)
    check(tag+': summary and three reports with names', '3 reports' in t and 'Avi Mizrahi' in t and 'Noa Shalev' in t and 'Rachel Amar' in t and '6 to 24 people, ages 9 to 67' in t, t[600:1600])
    check(tag+': no email address on the page', '@' not in t, [l for l in t.splitlines() if '@' in l])
    check(tag+': the no-responsibility message and the Moked Teva link are on the page', 'take no responsibility' in t and 'Moked Teva' in t)
    hrefs=await pg.eval_on_selector_all('.sheet .actions a','els=>els.map(e=>e.href)')
    check(tag+': Waze and Google Maps go to the start', 'waze.com/ul?q=Og%20trailhead' in hrefs[0] and 'google.com/maps/search' in hrefs[1], hrefs)
    await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_2_hike.png')
    await pg.eval_on_selector('.sheet-body','e=>e.scrollTo(0,e.scrollHeight)'); await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_2b_hike_end.png')
    # route file
    await pg.click('[data-hgpx]'); await pg.wait_for_selector('#hkModal')
    mt=await pg.inner_text('#hkModal'); check(tag+': route file box offers saving and names the two apps', 'Save the file' in mt and 'Israel Hiking Map' in mt and 'Amud Anan' in mt, mt)
    await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_3_gpx.png')
    async with pg.expect_download() as dl: await pg.click('#hkModal [data-g="save"]')
    d=await dl.value; path=await d.path(); body=open(path).read()
    check(tag+': the saved file is a .gpx named after the hike, with the route in it', d.suggested_filename=='Nahal-Og-lower-canyon.gpx' and '<gpx' in body and 'trkpt' in body, d.suggested_filename)
    await pg.click('#hkModal [data-g="x"]')
    # report after the hike
    await pg.click('.sheet .actions [data-hrep]'); await pg.wait_for_selector('#hrf')
    await pg.click('#hrSave'); check(tag+': a report without a date is refused', 'date you walked' in await pg.inner_text('#hrErr'))
    await pg.fill('#hrDate_il','01/10/2026'); await pg.press('#hrDate_il','Tab')
    await pg.fill('#hrSize','15'); await pg.fill('#hrA1','70'); await pg.fill('#hrA2','8'); await pg.click('#hrSave')
    check(tag+': youngest above oldest is refused', 'older than the oldest' in await pg.inner_text('#hrErr'))
    await pg.fill('#hrA1','8'); await pg.fill('#hrA2','70')
    await pg.click('[data-seg="difficulty"] [data-val="hard"]'); await pg.click('[data-seg="cliffs"] [data-val="yes"]'); await pg.click('[data-seg="water_shoes"] [data-val="useful"]')
    await pg.click('[data-seg="firing_zone"] [data-val="crosses"]'); await pg.click('#hrBath [data-k="start"]'); await pg.click('#hrBath [data-k="none"]')
    bp=await pg.eval_on_selector_all('#hrBath .tg[aria-pressed="true"]','els=>els.map(e=>e.dataset.k)'); check(tag+': choosing None clears the other bathroom answers', bp==['none'], bp)
    await pg.fill('#hrNote','<b>Sample</b> note & "quotes"'); await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_4_report.png')
    check(tag+': no route-file box on a hike that has one', await pg.query_selector('#hrFile') is None)
    await pg.click('#hrSave'); await pg.wait_for_selector('.sheet .hk-rep')
    t=await pg.inner_text('.sheet'); check(tag+': the new report shows, by Eretz Israel Tours, and the summary counts 4', '4 reports' in t and 'Walked 01/10/2026 · 15 people, ages 8 to 70' in t and 'Eretz Israel Tours' in t and '6 to 24 people, ages 8 to 70' in t, t[400:1500])
    check(tag+': typed text shows as text, not as markup', '<b>Sample</b> note & "quotes"' in t and await pg.query_selector('.sheet .hk-rep p b') is None)
    await pg.click('#closeS')
    # add a hike
    await pg.click('#addH'); await pg.wait_for_selector('#hkf')
    await pg.fill('#hkName','Sample new trail'); await pg.select_option('#hkRegion','Golan'); await pg.fill('#hkKm','4,5'); await pg.fill('#hkH1','2'); await pg.click('#hkSave')
    check(tag+': a hike not ticked as an official marked trail is refused', 'official marked trails' in await pg.inner_text('#hkErr'))
    await pg.check('#hkOff'); await pg.select_option('[data-mc="0"]','red'); await pg.fill('[data-mn="0"]','1234'); await pg.click('#hkMkAdd'); await pg.select_option('[data-mc="1"]','israel_trail')
    await pg.check('#hkSrcS'); await pg.fill('#hkUrl','https://example.org/x'); await pg.fill('#hkYear','2020'); await pg.click('#hkSave')
    check(tag+': a page older than 3 years is refused', 'older than 3 years' in await pg.inner_text('#hkErr'))
    await pg.fill('#hkYear',''); await pg.check('#hkLoop'); check(tag+': a loop hides the end location', await pg.is_hidden('#hkEndBox'))
    await pg.set_input_files('#hkFile', {'name':'not.gpx','mimeType':'text/plain','buffer':b'hello'}); await pg.wait_for_timeout(200)
    check(tag+': a file that is not GPX is refused', 'does not look like a GPX' in await pg.inner_text('#toast'))
    await pg.set_input_files('#hkFile', {'name':'one.gpx','mimeType':'application/gpx+xml','buffer':b'<?xml version="1.0"?><gpx version="1.1"><trk><trkseg><trkpt lat="33.0" lon="35.7"></trkpt></trkseg></trk></gpx>'}); await pg.wait_for_timeout(200)
    check(tag+': a GPX file with a single point is refused', 'no route in it' in await pg.inner_text('#toast'))
    RAW=b'<?xml version="1.0" encoding="UTF-8"?><!-- made by an app --><gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="x y" version="1.1" creator="SomeApp"><metadata><name>Sample family 01/09/2026</name><author><name>Sample Walker</name><email id="walker" domain="example.com"/></author><time>2026-09-01T05:15:00Z</time></metadata><wpt lat="33.01" lon="35.71"><ele>410.25</ele><time>2026-09-01T05:20:00Z</time><name>Spring</name></wpt><trk><name>Sample family morning walk</name><extensions><x:hr xmlns:x="urn:x">120</x:hr></extensions><trkseg><trkpt lat="33.0000001" lon="35.7"><ele>400</ele><time>2026-09-01T05:15:00Z</time><extensions><x:hr xmlns:x="urn:x">99</x:hr></extensions></trkpt><trkpt lat="33.002" lon="35.702"><time>2026-09-01T05:16:00Z</time></trkpt></trkseg></trk></gpx>'
    await pg.set_input_files('#hkFile', {'name':'Sample family 2026-09-01 0715.gpx','mimeType':'application/gpx+xml','buffer':RAW}); await pg.wait_for_timeout(200)
    check(tag+': a GPX file is taken, and its own name is not shown', 'ready to save' in await pg.inner_text('#hkFileN') and 'Sample family' not in await pg.inner_text('#hkFileN'))
    await pg.fill('#hkStart','Car park https://evil.example/login?x=1')
    await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_5_add.png'); await pg.click('#hkSave'); await pg.wait_for_selector('.sheet .actions')
    t=await pg.inner_text('.sheet'); check(tag+': the new hike opens: 4.5 km, markers, unverified, no date on the page, route file', all(x in t for x in ('4.5 km','Red, trail 1234','Israel Trail','Unverified','no date on the page','On file','A loop')), t[:900])
    hrefs=await pg.eval_on_selector_all('.sheet .actions a','els=>els.map(e=>e.href)')
    check(tag+': a link that is not a map link never becomes a button, and stays in view as text', all('evil.example/login' not in h.split('q=')[0].split('query=')[0] and (h.startswith('https://waze.com/') or h.startswith('https://www.google.com/maps/')) for h in hrefs) and 'https://evil.example/login?x=1' in t, hrefs)
    await pg.click('[data-hgpx]'); await pg.wait_for_selector('#hkModal')
    async with pg.expect_download() as dl2: await pg.click('#hkModal [data-g="save"]')
    d2=await dl2.value; body2=open(await d2.path()).read(); await pg.click('#hkModal [data-g="x"]')
    check(tag+': the kept route file holds the route only: no name, email, times, extra data, recording name or comment', all(x not in body2 for x in ('Sample','Walker','example.com','time','extensions','hr','made by','schemaLocation','metadata')) and body2.count('<trkpt')==2 and '<name>Spring</name>' in body2 and 'lat="33"' in body2 and '<ele>410.3</ele>' in body2, body2)
    check(tag+': and it is saved under the hike\'s name, not the file\'s', d2.suggested_filename=='Sample-new-trail.gpx', d2.suggested_filename)
    await pg.click('#closeS')
    # as a guide
    await pg.select_option('#demoAs','guide'); await pg.wait_for_selector('#hkResults .row')
    rows=await pg.eval_on_selector_all('#hkResults .row .row-name','els=>els.map(e=>e.textContent)')
    check(tag+': another guide does not see Noa\'s waiting hike', 'Nahal Amud, upper part' not in rows and len(rows)==8, rows)
    await pg.click('#hkResults .row:has-text("Nahal Og")'); await pg.wait_for_selector('.sheet .hk-rep'); t=await pg.inner_text('.sheet')
    check(tag+': the guide can change only his own report', (await pg.eval_on_selector_all('.sheet [data-redit]','e=>e.length'))==1 and 'Suggest a change' in t and 'Change details' not in t and 'Take this hike off' not in t)
    await pg.click('[data-hsug]'); await pg.fill('#hsT','The trailhead moved.'); await pg.click('#hsSend'); await pg.wait_for_selector('.sheet .hk-rep'); await pg.click('#closeS')
    await pg.click('#addH'); await pg.fill('#hkName','Guide sample trail'); await pg.select_option('#hkRegion','Galilee'); await pg.check('#hkOff'); await pg.fill('#hkKm','3'); await pg.fill('#hkH1','1'); await pg.click('#hkSave'); await pg.wait_for_selector('.sheet .actions')
    t=await pg.inner_text('.sheet'); check(tag+': a guide\'s new hike waits for approval and he can still change it', 'Waiting for approval' in t and 'Change details' in t, t[:300]); await pg.click('#closeS')
    # as an organisation
    await pg.select_option('#demoAs','org'); await pg.wait_for_selector('#hkResults .row')
    tabs=await pg.eval_on_selector_all('.tab', 'els=>els.map(e=>e.textContent.trim())'); rows=await pg.eval_on_selector_all('#hkResults .row .row-name','els=>els.map(e=>e.textContent)')
    check(tag+': an organisation keeps the Hikes tab and has no Jobs tab', 'Hikes' in tabs and 'Jobs' not in tabs, tabs)
    check(tag+': an organisation sees the approved hikes only', 'Guide sample trail' not in rows and 'Nahal Amud, upper part' not in rows and 'Sample new trail' in rows, rows)
    await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_6_org.png', full_page=True)
    await pg.click('#hkResults .row:has-text("Sataf")'); await pg.wait_for_selector('.sheet .hk-rep'); t=await pg.inner_text('.sheet')
    check(tag+': the organisation sees its own report marked and can add one', 'YOU' in t.upper() and (await pg.eval_on_selector_all('.sheet [data-redit]','e=>e.length'))==1 and '@' not in t); await pg.click('#closeS')
    # back as Eretz Israel Tours: the review queue
    await pg.select_option('#demoAs','admin'); await pg.wait_for_selector('.tabs'); await pg.click('.tab[data-tab="review"]'); await pg.wait_for_selector('.panel')
    t=await pg.inner_text('#view'); check(tag+': Review tab lists the two waiting hikes', 'New hikes to check' in t and 'Guide sample trail' in t and 'Nahal Amud, upper part' in t, t[:400])
    fb=await pg.inner_text('#view'); check(tag+': the suggested change reached Feedback with the hike named', 'The trailhead moved.' in fb and 'Hike: Nahal Og' in fb)
    await pg.wait_for_timeout(450); await pg.screenshot(path=OUT+tag+'_7_review.png')
    await pg.click('[data-hkok]'); await pg.wait_for_timeout(300); t=await pg.inner_text('#view')
    check(tag+': approving takes it out of the queue', t.count('data-hkok')==0 and (await pg.eval_on_selector_all('[data-hkok]','e=>e.length'))==1)
    await pg.click('.tab[data-tab="team"]'); await pg.wait_for_selector('#hkAll'); check(tag+': Team tab has the Hikes switch, off', not await pg.is_checked('#hkAll'))
    await pg.click('.tab[data-tab="hikes"]'); await pg.wait_for_selector('#hkResults .row')
    await b.close()
async def main():
    async with async_playwright() as p:
        await run(p, 390, 844, 'phone'); await run(p, 1280, 800, 'desk')
    for e in errs: print('ERR', e)
    print('\n%d checks, %d failed, %d page errors' % (len(res), sum(1 for _,ok in res if not ok), len(errs)))
asyncio.run(main())
